project:
  type: book

book:
  title: "Applied Artificial Intelligence and Deep Learning Book"
  author:
    - name: Tim Mayer
      affiliations:
        - id: nasa-earthtrise
          name: NASA - EarthRISE
        - id: UofA-huntsville
          name: The University of Alabama in Huntsville
    - name: Biplov Bhandari
      affiliations:
        - id: ert
          name: Earth Resources Technology
    - name: David Saah
      affiliations:
        - id: USF
          name: University of San Francisco
        - id: spatial-informatics-group
          name: Spatial Informatics Group

  date: "6/1/2026"
  cover-image: Images/Book_Cover.png
  repo-url: https://github.com/NASA-EarthRISE/EarthRISE-Applied-Artificial-Intelligence-and-Deep-Learning-Book
  repo-actions: [source, edit, issue]
  downloads: [pdf]
  chapters:
      - index.md
      - 02-Data-Preparation/index.ipynb
      - part: "Semantic Segmentation"
        chapters:
          - 03_Semantic_Segmentation/01__Crop_Mapping/notebooks/Rice_Mapping_Bhutan_2021.ipynb
          - 03_Semantic_Segmentation/02__Selective_Logging_Detection/notebooks/2_model_training.ipynb
      - 04_Object_Detection/index.ipynb
      - part: "Time Series"
        chapters:
          - 05_Time_Series/01__Soybean_Yield_Prediction/notebooks/Crop_yield_estimationR4.ipynb
      - 06_Eco_Process_Sim/01_Active_Fire_Detection/notebook/BNN_Active_Fire_Detection.ipynb
      - 07_Transfer_Learning/index.ipynb
      - 08_Fusion/index.ipynb
      - 09_Downscaling/index.ipynb
      - part: "Future of Deep Learning and Foundational Models"
        chapters:
          - 10_Future/01_Evaluating_Foundation_Models_Trained_with_Earth_Observation_Data/Chapter_Practical_EOFM_Evaluation.ipynb
      - 11_Ethics/index.ipynb
      - 12_Conclusions/index.ipynb
      - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly
    page-tools: ["colab", "github", "source", "edit", "issue"]
    includes:
      before-body: _includes/ga.html
  pdf:
      documentclass: scrreprt
      page-tools: []
      code-fold: false
      output-fold: false
      keep-tex: false
      fig-format: png
      header-includes:
        - \usepackage{graphicx}
        - \newenvironment{CSLReferences}[2]{}{}

execute:
  enabled: false
